### ISSUE TITLE
Add remaining primitive parameters to GUI

### ISSUE THREAD

**Issue by danielway** [jakedv24/senior-design-sdmay21-26#16]
Add all remaining primitive parameters (`bool` and `float` type) to the Swing GUI, with validation for the ranges specified in Dr. Cohen's "FBA_GUI_model-for SD.xlsx" spreadsheet.

Completion of this task requires the field be shown on the screen and logic exists to both validate that the field falls into the specified range and extract the value of the field into a variable of the same type.

**Acceptance criteria**
- [x] All primitive-type fields (`bool` and `float`) exist in the GUI
- [x] Those primitive fields are validated according to the specified ranges
- [x] Those fields' values are extracted into variables of the same type, for later use in instantiating jobs

![image](https://user-images.githubusercontent.com/1724257/94028026-1bf6f780-fd81-11ea-80b8-7be448ae65e0.png)

**Comment by DaultonLeach** [comment]
Update: The GUI has all of the following fields. I am currently adding the logic to hand off all the GUI variables to the driver. This also performs checks on correct entries to the GUI. 

Fair warning. There is a ton of duplicate code being introduced that can be compacted into methods. I am aware of this, but I want to get all the fields working, so the person working on the driver taking and reading this values isn't hung up waiting for me. After iteration 1 I am going to be doing some refactoring.

**Comment by DaultonLeach** [comment]
Issue done. :)
