### ISSUE TITLE
Implement the "Gene Knockouts" GUI input

### ISSUE THREAD

**Issue by danielway** [jakedv24/senior-design-sdmay21-26#19]
Add the Gene Knockouts field to the Swing GUI.

Given the analysis from #17 and #18, implement the multiple-selection set input for Gene Knockouts.

Completion of this task requires the field be shown on the screen with logic to extract the user's selections into a Java data structure, which can then be used to instantiate a job.

**Acceptance criteria**
- [ ] The Gene Knockouts field is visible on the GUI
- [ ] The user's selection is extracted into a reasonable Java data structure for later use in instantiating jobs

![image](https://user-images.githubusercontent.com/1724257/94028736-beaf7600-fd81-11ea-85b2-c2b2922ece6a.png)

**Comment by danielway** [comment]
FYI @PukTheGreat this will be blocked by #17 and #18.

**Comment by DaultonLeach** [comment]
Completed. Never Closed
