### ISSUE TITLE
Implement the "Reaction Knockouts" GUI input

### ISSUE THREAD

**Issue by danielway** [jakedv24/senior-design-sdmay21-26#21]
Add the Reaction Knockouts field to the Swing GUI.

Given the analysis from #17 and #18, implement the multiple-selection set input for Reaction Knockouts.

Completion of this task requires the field be shown on the screen with logic to extract the user's selections into a Java data structure, which can then be used to instantiate a job.

**Acceptance criteria**
- [ ] The Reaction Knockouts field is visible on the GUI
- [ ] The user's selection is extracted into a reasonable Java data structure for later use in instantiating jobs

![image](https://user-images.githubusercontent.com/1724257/94029406-64fb7b80-fd82-11ea-9feb-2e3365bbba09.png)

**Comment by DaultonLeach** [comment]
Completed. Never Closed
