### ISSUE TITLE
Implement the "Media Supplement" GUI input

### ISSUE THREAD

**Issue by danielway** [jakedv24/senior-design-sdmay21-26#23]
Add the Media Supplement field to the Swing GUI.

Given the analysis from #17 and #18, implement the single-selection input for Media Supplement.

Completion of this task requires the field be shown on the screen with logic to extract the user's selections into a Java data structure, which can then be used to instantiate a job.

**Acceptance criteria**
- [ ] The Media Supplement field is visible on the GUI
- [ ] The user's selection is extracted into a reasonable Java data structure for later use in instantiating jobs

![image](https://user-images.githubusercontent.com/1724257/94030107-100c3500-fd83-11ea-84dc-69b34d4a4b47.png)

**Comment by DaultonLeach** [comment]
Issue completed per most recent pull request.
