### ISSUE TITLE
Analyze automating the rich KBase selection input

### ISSUE THREAD

**Issue by danielway** [jakedv24/senior-design-sdmay21-26#25]
Analyze the rich single- or multiple-selection (depends on the particular field) input in KBase so we can better-plan for writing code to automate interactions with it.

- What steps are necessary to get the input "ready" for us to make the user's selections?
- How can we match the user's selections in our data structure with the options in the input?
- How do we make selections with the input?

**Acceptance Criteria**
- [ ] Detailed definition around the steps to interact with KBase's rich selection input
- [ ] Bonus points if you can identify ways to select things with Selenium (class names, CSS selector snippets, whatever might help with implementation)

![image](https://user-images.githubusercontent.com/1724257/94031547-970ddd00-fd84-11ea-9be8-ae32d5478cb6.png)

**Comment by clmeyer42** [comment]
on FBA there are two rich selectors
data-parameter="target_reaction" Reaction to maximize
data-parameter="reation_ko_list" Reaction Knockouts

data-element="available-items-area" each parameter has there own available-items-area (the page has a total of 4)
each available-item-area has four navigation buttons class="btn btn-default" type="button
super up is first, has child element of class="fa fa-step-forward fa-rotate-270: 
normal up is second, has child element of class="fa fa-caret-up"
normal down is third ,has child element of class="fa fa-caret-dwont"
super down is fourth, has child element of class="fa fa-step-forward fa-rotate-90"


buttons 5-9 buttons are used for selecting which element to add(class="kb-btn-icon" type=button" data-item-id="[name of object]"
[name of object] examples: bio1, rxn00001_c0, rxn00001_d0;
if the search box is used (data-element="search-box">) the number of selector buttons will decrease.
the selector buttons can be found under (data-element="available-items")


For reaction to maximize selecting a button will disable all other selector buttons except itself
An addtional button will appear under (data-element="selected-items") clicking this button or the orginal button will
renable the other buttons as well remove the addtional button

FOr reaction knockouts clicking a selector button will not disable the other buttons, 
and for each selector clicked a button will appear under (data-element="available-items")
clicking one of those buttons will make it disaaper and will unselect the corresponding selector button.
